#!/bin/sh

COLOR_RED=$(printf '\033[0;31m')
COLOR_GREEN=$(printf '\033[0;92m')
COLOR_DEFAULT=$(printf '\033[0m')

conflicts=`git diff --cached --name-only -G"<<<<<|=====|>>>>>"`

if [[ -n "$conflicts" ]]; then
    echo "****************************************"
    echo " "
    echo "${COLOR_RED}Unresolved merge conflicts in these files:${COLOR_DEFAULT}"
    for conflict in $conflicts; do
        echo "${COLOR_GREEN} - $conflict${COLOR_DEFAULT}"
    done;
    echo " "
    echo "${COLOR_RED}Please fix them and then you can commit your files.${COLOR_DEFAULT}"
    echo " "
    echo "****************************************"
    exit 77 # permission denied
fi

exit 0
